#define TARGET_NUMBER 4000000

#include <stdio.h>
#include <stdbool.h> // bool type suppor

/*
Problem 2
Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, 
find the sum of the even-valued terms.
*/

bool is_even(int);

int main()
{
    int sum = 0;
    // Set first two fibonacci numbers
    int previous_fibonacci = 0, current_fibonacci = 1;

    while (current_fibonacci < TARGET_NUMBER)
    {
        if (is_even(current_fibonacci))
            sum += current_fibonacci;

        // Compute next fibonacci
        int next_fibonacci = previous_fibonacci + current_fibonacci;
        previous_fibonacci = current_fibonacci;
        current_fibonacci = next_fibonacci;
    }

    printf("Sum of even-fibonacci numbers below %d is, %d\n", TARGET_NUMBER, sum);

    return 0;
}

bool is_even(int number)
{
    return (number & 1) ? false : true;
}

/* Result
Sum of even-fibonacci numbers below 4000000 is, 4613732
*/