/*******************************************************************************
Author: Zake Jeonghwan Lee
Date: 08/08/2020

Problem 2
Each new term in the Fibonacci sequence is generated by adding the previous two 
terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed 
four million, find the sum of the even-valued terms.
*******************************************************************************/

#include <stdio.h> /* printf */
#include <stdbool.h> /* bool type support */

#define TARGET_NUMBER 4000000 /* constant - given constraint */

bool isEven(int);

/*******************************************************************************
main
*******************************************************************************/
int main()
{
    int sum = 0;
    /* Set first two fibonacci numbers */
    int previousFibonacci = 0, currentFibonacci = 1;

    while (currentFibonacci < TARGET_NUMBER)
    {
        if (isEven(currentFibonacci))
            sum += currentFibonacci;

        // Compute next fibonacci
        int nextFibonacci = previousFibonacci + currentFibonacci;
        previousFibonacci = currentFibonacci;
        currentFibonacci = nextFibonacci;
    }

    printf("\nSum of even-fibonacci numbers below %d is, %d\n", TARGET_NUMBER, sum);

    return 0;
}

/*******************************************************************************
isEven
This function compares and returns whether the given number is an even number
inputs:
- number: positive integer number
outputs:
- boolean value whether the given number is an even number
*******************************************************************************/
bool isEven(int number)
{
    return (number & 1) ? false : true;
}

/*******************************************************************************
Result

Sum of even-fibonacci numbers below 4000000 is, 4613732
*******************************************************************************/